AWSTemplateFormatVersion: 2010-09-09
Description: aws-study template

Resources:

  # vpcの作成
  awsvpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: default

  # igwの作成
  MyInternetGateway:
    Type: AWS::EC2::InternetGateway

  # igwの接続設定
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref awsvpc
      InternetGatewayId: !Ref MyInternetGateway
  
  # パブリックサブネット1aの作成
  PublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref awsvpc
      CidrBlock: 10.0.0.0/20
      AvailabilityZone: ap-northeast-1a

  # パブリックサブネット1cの作成
  PublicSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref awsvpc
      CidrBlock: 10.0.16.0/20
      AvailabilityZone: ap-northeast-1c

  # プライベートサブネット1aの作成
  PrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref awsvpc
      CidrBlock: 10.0.128.0/20
      AvailabilityZone: ap-northeast-1a

  # プライベートサブネット1cの作成
  PrivateSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref awsvpc
      CidrBlock: 10.0.144.0/20
      AvailabilityZone: ap-northeast-1c

  # パブリックルートテーブルの作成
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref awsvpc

  # パブリックルートの設定
  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway

   # パブリックサブネット1aをルートテーブルに関連付け
  PublicRouteTableAssociation1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1a
      RouteTableId: !Ref PublicRouteTable

  # パブリックサブネット1cをルートテーブルに関連付け
  PublicRouteTableAssociation1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1c
      RouteTableId: !Ref PublicRouteTable

  # vpcエンドポイントの作成（ゲートウェイ型）
  VPCS3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      RouteTableIds:
        - !Ref PrivateRouteTable1a #プライベートルートテーブル1aの指定
        - !Ref PrivateRouteTable1c #プライベートルートテーブル1cの指定
      VpcId: !Ref awsvpc
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3  # S3のVPCエンドポイントを指定
      VpcEndpointType: Gateway # ゲートウェイ型の指定

  # プライベートルートテーブル1aの作成
  PrivateRouteTable1a:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref awsvpc

  # プライベートルート1aの設定
  PrivateRoute1a:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable1a
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref VPCS3Endpoint
  
  # プライベートサブネット1aをルートテーブルに関連付け
  PrivateRouteTableAssociation1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1a
      RouteTableId: !Ref PrivateRouteTable1a

    # プライベートルートテーブル1cの作成
  PrivateRouteTable1c:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref awsvpc

  # プライベートルート1cの設定
  PrivateRoute1c:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable1c
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref VPCS3Endpoint
  
  # プライベートサブネット1cをルートテーブルに関連付け
  PrivateRouteTableAssociation1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1c
      RouteTableId: !Ref PrivateRouteTable1c

  # セキュリティグループの作成（プライベートサブネット1a用）
  PrivateInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for private instances"
      VpcId: !Ref awsvpc
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: "-1"
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0

  # キーペアの作成
  NewKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: awsstudykeypair

  # EC2の作成
  awsstudyec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-027fff96cc515f7bc
      InstanceType: t2.micro
      KeyName: !Ref NewKeyPair
