---
- name: Install Java 21
  hosts: web
  become: true

  tasks:
    - name: Install Amazon Corretto 21
      ansible.builtin.yum:
        name: java-21-amazon-corretto
        state: present

    - name: Verify Java is installed
      ansible.builtin.command: java -version
      register: java_version
      changed_when: false

    - name: Display Java version
      ansible.builtin.debug:
        var: java_version.stdout
