---
- name: Install Java on EC2
  hosts: web
  become: true
  tasks:
    - name: Ensure package cache is up to date (Amazon Linux / RHEL / CentOS)
      ansible.builtin.yum:
        update_cache: yes

    - name: Install OpenJDK 17
      ansible.builtin.yum:
        name: java-17-amazon-corretto
        state: present

    - name: Check Java version
      ansible.builtin.command: java -version
      register: java_version
      changed_when: false

    - name: Show installed Java version
      ansible.builtin.debug:
        var: java_version.stderr_lines
