name: Ansible Deploy

on:
  pull_request:
    paths:
      - 'tfpractice/**.tf'
      - 'tfpractice/modules/**.tf'
      - 'tfpractice/modules/**.tftest.hcl'
      - '.github/workflows/**.yml'
      - 'ansible/**.yml'
      - 'ansible/**.ini'
  workflow_dispatch:

jobs:
  ansible-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      # Ansibleインストール
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install ansible ansible-lint

      # SSH秘密鍵の設定
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 構文チェック
      - name: Syntax Check
        run: |
          ansible-playbook -i ansible/inventory.ini --syntax-check ansible/install_springboot.yml

      # Lint
      - name: Lint Check
        run: |
          ansible-lint ansible/install_springboot.yml

      # ドライラン
      - name: Dry 
        working-directory: ansible
        run: |
          ansible-playbook -i inventory.ini --check install_springboot.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"

  ansible-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      # Ansibleインストール
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install ansible

      # SSH秘密鍵の設定
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 本番デプロイ
      - name: Run Ansible Playbook
        working-directory: ansible
        run: |
          ansible-playbook -i inventory.ini install_springboot.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
