name: Debug Ansible Config Loading

on:
  workflow_dispatch:

jobs:
  debug-ansible-config:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: AWS 認証情報を設定
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: AWS CLI & Ansible をインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install ansible boto3 botocore awscli
          ansible-galaxy collection install amazon.aws community.aws --collections-path /home/runner/.ansible/collections
          ansible-galaxy collection list

      - name: ansible.cfg をリポジトリルートに生成（正しい書き方）
        run: |
          cat <<'EOF' > ansible.cfg
          [defaults]
          collections_path = /home/runner/.ansible/collections
          host_key_checking = False
          retry_files_enabled = False
          interpreter_python = auto_silent
          EOF

      - name: 作成した ansible.cfg の内容確認
        run: cat ansible.cfg

      - name: カレントディレクトリとファイル一覧の確認
        run: |
          pwd
          ls -l
          ls -l /home/runner/.ansible/collections

      - name: 環境変数確認
        run: env

      - name: ansible --version
        run: ansible --version

      - name: ansible-config dump で設定確認
        run: ansible-config dump | grep -i collection

      - name: ansible-doc で SSM コネクションプラグイン確認
        run: ansible-doc -t connection amazon.aws.aws_ssm

      - name: ダミーインベントリファイルを作成
        run: |
          echo "[web]" > inventory.ini
          echo "ssm-ec2 ansible_host=i-0123456789abcdef0 ansible_connection=amazon.aws.aws_ssm ansible_region=ap-northeast-1" >> inventory.ini
          cat inventory.ini

      - name: Ansible Playbook 実行テスト（接続チェック用）
        env:
          ANSIBLE_CONFIG: ${{ github.workspace }}/ansible.cfg
          ANSIBLE_COLLECTIONS_PATHS: /home/runner/.ansible/collections
        run: |
          ansible all -i inventory.ini -m ping -vvv || echo "ping failed (expected if instance is dummy)"
